# Generated by Django 6.0.2 on 2026-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
