# Generated by Django 6.0.2 on 2026-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='mood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='water_intake',
            field=models.IntegerField(),
        ),
    ]
