# Generated by Django 6.0.2 on 2026-02-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_healthlog_options_alter_healthlog_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
