# Generated by Django 6.0.2 on 2026-02-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_healthlog_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='exercise_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='water_intake',
            field=models.PositiveIntegerField(),
        ),
    ]
