# Generated by Django 6.0.2 on 2026-02-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_healthlog_exercise_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthlog',
            name='water_intake',
        ),
        migrations.AddField(
            model_name='healthlog',
            name='water_liters',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='exercise_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='sleep_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
