# Generated by Django 6.0.2 on 2026-02-23 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_healthlog_water_intake_healthlog_water_liters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='healthlog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='healthlog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='exercise_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='water_liters',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
